
_partial_: true
_target_: goo.augmentations.paws_orig.DataAugmentationPAWS
global_crops_scale: [0.14, 1.0]
local_crops_scale: [0.05, 0.14]
global_crops_number: 2
local_crops_number: 6
global_crop_size: 224
local_crop_size: 96
color_distortion_s : 0.5
blur_prob: 0.0
color_distortion_grayscale : False
color_distortion_solarize : True
color_distortion_equalize : True
normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
