# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  # - override hydra_logging: disabled  
  # - override job_logging: disabled  
  # - override job_logging: none
  # - override hydra_logging: none  
  # - override job_logging: custom

# output directory, generated dynamically on each run

job:
  name: ${paths.log_dir}/${task_name}_${seed}/main

run:
  dir: ${paths.log_dir}/${task_name}_${seed}/
sweep:
  dir: ${paths.log_dir}/${task_name}_${seed}/
  subdir: ${hydra.job.num}
